"use client"

import { Badge, Box, Button, Flex, IconButton, Popover, Portal, Stack, Text } from "@chakra-ui/react"
import { Bell } from "lucide-react"
import { useMemo } from "react"

import { defaultNNotificationCenterLabels, resolveLabels } from "./labels"
import type { NNotificationCenterProps } from "./types"

export function NNotificationCenter({ notifications, trigger, onSelect, onMarkRead, onMarkAllRead, labels: custom, unstyled = false, classNames, styles }: NNotificationCenterProps) {
  const labels = useMemo(() => resolveLabels(defaultNNotificationCenterLabels, custom), [custom])
  const unread = notifications.filter((item) => !item.read).length
  return <Box display="contents" className={classNames?.root} css={styles?.root} data-scope="n-notification-center" data-part="root"><Popover.Root positioning={{ placement: "bottom-end" }}><Popover.Trigger asChild>{trigger ?? <IconButton unstyled={unstyled} variant={unstyled ? undefined : "ghost"} aria-label={`${labels.trigger}. ${labels.unreadCount(unread)}`} position="relative" className={classNames?.trigger} css={styles?.trigger} data-part="trigger"><Bell size={19} />{unread ? <Badge position="absolute" top="0" insetInlineEnd="0" size="xs" colorPalette="red">{unread > 99 ? "99+" : unread}</Badge> : null}</IconButton>}</Popover.Trigger><Portal><Popover.Positioner><Popover.Content unstyled={unstyled} width={{ base: "calc(100vw - 2rem)", sm: "24rem" }} maxH="min(32rem, calc(100dvh - 6rem))" className={classNames?.content} css={styles?.content} data-scope="n-notification-center" data-part="content"><Popover.Arrow /><Popover.Header unstyled={unstyled} className={classNames?.header} css={styles?.header} data-part="header"><Flex justify="space-between" align="center" gap="3"><Popover.Title>{labels.title}</Popover.Title>{unread && onMarkAllRead ? <Button size="xs" variant="plain" onClick={onMarkAllRead}>{labels.markAllRead}</Button> : null}</Flex></Popover.Header><Popover.Body unstyled={unstyled} overflowY="auto" p={unstyled ? undefined : "0"}>{notifications.length ? <Stack gap="0" className={classNames?.list} css={styles?.list} data-part="list">{notifications.map((item) => <Button key={item.id} variant={unstyled ? undefined : "ghost"} unstyled={unstyled} height="auto" justifyContent="start" rounded={unstyled ? undefined : "0"} p={unstyled ? undefined : "3"} whiteSpace="normal" bg={!unstyled && !item.read ? "colorPalette.subtle" : undefined} onClick={() => { onMarkRead?.(item.id); onSelect?.(item) }} className={classNames?.item} css={styles?.item} data-part="item"><Flex gap="3" textAlign="start" width="full">{item.icon ? <Box flexShrink="0">{item.icon}</Box> : null}<Stack gap="1" minW="0"><Text fontWeight={!item.read ? "bold" : "medium"}>{item.title}</Text>{item.description ? <Text textStyle="sm" color="fg.muted">{item.description}</Text> : null}{item.timestamp ? <Text textStyle="xs" color="fg.muted">{item.timestamp}</Text> : null}</Stack></Flex></Button>)}</Stack> : <Text color="fg.muted" p={unstyled ? undefined : "5"} textAlign="center" className={classNames?.empty} css={styles?.empty} data-part="empty">{labels.empty}</Text>}</Popover.Body></Popover.Content></Popover.Positioner></Portal></Popover.Root></Box>
}
