import type { NFactureLabels } from "./types"

export const defaultNFactureLabels: NFactureLabels = {
  moduleName: "NFacture",
  moduleDescription: "Facturación electrónica CFDI 4.0 para México",
  navigationLabel: "Navegación de facturación",
  dashboard: "Resumen",
  issue: "Emitir factura",
  history: "Historial y comprobantes",
  ticket: "Facturar ticket",
  administration: "Configuración SAT y PAC",
  certificates: "Certificados CSD y fiscal",
  catalogs: "Mapeo de catálogos SAT",
  integrations: "API y sistemas externos",
  documentation: "Documentación",
  roleLabel: "Rol de facturación",
  adminRole: "Administrador",
  operatorRole: "Operador",
  posRole: "Punto de venta",
  loading: "Cargando facturación",
  loadError: "No fue posible cargar la información de facturación.",
  retry: "Reintentar",
  stampedMetric: "Timbradas",
  cancelledMetric: "Canceladas",
  pendingMetric: "Pendientes",
  errorMetric: "Con error",
  recentInvoices: "Comprobantes recientes",
  customer: "Receptor",
  customerPlaceholder: "Selecciona RFC o razón social",
  customerHelp: "Los datos deben coincidir con la Constancia de Situación Fiscal del receptor.",
  addCustomer: "Registrar receptor",
  newCustomerTitle: "Nuevo receptor fiscal",
  newCustomerDescription: "Captura los datos exactamente como aparecen en la Constancia de Situación Fiscal.",
  customerName: "Nombre o razón social",
  postalCode: "Código postal fiscal",
  taxRegime: "Régimen fiscal",
  email: "Correo electrónico",
  saveCustomer: "Guardar receptor",
  customerCreated: "El receptor se registró correctamente.",
  customerCreateError: "No fue posible registrar el receptor.",
  invalidRfc: "El RFC del receptor no tiene una estructura válida.",
  concepts: "Conceptos",
  cfdiUse: "Uso del CFDI",
  paymentForm: "Forma de pago",
  paymentMethod: "Método de pago",
  currency: "Moneda",
  subtotal: "Subtotal",
  discount: "Descuento",
  vat: "IVA",
  ieps: "IEPS",
  total: "Total",
  stamp: "Validar y timbrar CFDI",
  stamping: "Timbrando CFDI",
  stampSuccess: "El CFDI se timbró correctamente.",
  stampError: "El PAC rechazó la solicitud de timbrado.",
  missingCustomer: "Selecciona un receptor.",
  missingLines: "Agrega al menos un concepto.",
  incompatibleUse: "El uso de CFDI no es compatible con el régimen fiscal del receptor.",
  invoiceGrid: "Partidas de la factura",
  ticketFolio: "Folio o identificador del ticket",
  ticketPlaceholder: "Ej. TKT-1048",
  searchTicket: "Buscar ticket",
  searchingTicket: "Buscando ticket",
  ticketNotFound: "No se encontró un ticket con ese folio.",
  ticketAlreadyInvoiced: "Este ticket ya fue facturado.",
  ticketReady: "Ticket encontrado. Revisa los conceptos antes de timbrar.",
  certificateTitle: "Certificados de sello digital",
  certificateDescription: "Carga el certificado .cer, la llave .key y valida su vigencia mediante tu adaptador seguro.",
  certificateFile: "Certificado CSD (.cer)",
  privateKeyFile: "Llave privada (.key)",
  privateKeyPassword: "Contraseña de la llave privada",
  inspectCertificate: "Validar certificado",
  inspectingCertificate: "Validando certificado",
  certificateHint: "Los archivos y secretos deben procesarse en infraestructura segura; NFacture no los persiste.",
  validCertificate: "Certificado vigente",
  invalidCertificate: "No fue posible validar el certificado.",
  pacTitle: "Proveedor autorizado de certificación",
  pacDescription: "Configura un PAC autorizado y separa las credenciales de pruebas y producción.",
  pacProvider: "Proveedor PAC",
  environment: "Ambiente",
  sandbox: "Pruebas",
  production: "Producción",
  apiKey: "API key",
  savePac: "Guardar conexión",
  pacSaved: "Conexión PAC guardada.",
  mappingTitle: "Mapeo de productos con catálogos SAT",
  mappingDescription: "Relaciona cada SKU interno con ClaveProdServ y ClaveUnidad antes de emitir.",
  integrationTitle: "Integración externa",
  integrationDescription: "Conecta POS, ERP o e-commerce mediante adaptadores, API keys y webhooks administrados por tu backend.",
  noData: "No hay información disponible.",
  statusStamped: "Timbrada",
  statusPending: "Pendiente",
  statusCancelled: "Cancelada",
  statusError: "Error",
  folio: "Folio",
  issuedAt: "Fecha de emisión",
  rfc: "RFC",
  status: "Estado",
  satKey: "Clave SAT",
  quantity: "Cantidad",
  unitPrice: "Precio unitario",
  sku: "SKU",
  productOrService: "Producto o servicio",
  productServiceKey: "ClaveProdServ",
  unitKey: "ClaveUnidad",
  actions: "Acciones del comprobante",
  downloadPdf: "Descargar PDF",
  downloadXml: "Descargar XML",
  resendEmail: "Reenviar por correo",
  viewDocument: "Ver comprobante",
  documentPreview: "Vista previa del comprobante",
  taxStatusFile: "Constancia de Situación Fiscal (PDF)",
  inspectTaxStatus: "Leer constancia fiscal",
  fiscalProfileReady: "Datos fiscales detectados",
  generateApiKey: "Generar API key",
  generatedApiKey: "Copia esta clave ahora; no volverá a mostrarse.",
  webhookEndpoint: "Endpoint del webhook",
  saveWebhook: "Guardar webhook",
  integration: "Integración",
  integrationType: "Tipo",
  openConfiguration: "Abrir configuración",
  manageCatalogs: "Administrar mapeo",
  viewDocumentation: "Consultar documentación",
  documentationTitle: "Documentación de NFacture",
  documentationDescription: "Contratos breves para integrar datos, navegación y seguridad sin abandonar el módulo.",
  docsIntegration: "Integración",
  docsNavigation: "Navegación",
  docsSecurity: "Seguridad",
  docsIntegrationBody: "Inyecta colecciones y un NFactureDataAdapter mediante NissiInvoicingProvider. El adaptador conecta tu API, POS, ERP o PAC.",
  docsNavigationBody: "Usa createNFactureNavigation con NSidebar o createNFactureHeaderNavigation con NHeader. Ambas variantes conservan vista, ruta y permisos por rol.",
  docsSecurityBody: "CSD, llaves privadas, API keys, timbrado y autorización definitiva deben permanecer en infraestructura segura del consumidor.",
  fiscalNotice: "La UI hace validaciones preventivas. El backend y el PAC deben revalidar catálogos, certificados, XML, identidad y reglas fiscales vigentes.",
}

export function resolveNFactureLabels(labels?: Partial<NFactureLabels>): NFactureLabels {
  return { ...defaultNFactureLabels, ...labels }
}
