import { Box, Card, Flex, Grid, Icon, Stack, Text } from "@chakra-ui/react"
import { Check, Minus } from "lucide-react"

import type { NPlanComparisonLabels, NPlanComparisonProps } from "./types"

export const defaultNPlanComparisonLabels: NPlanComparisonLabels = { feature: "Característica", included: (feature, plan) => `${feature} incluida en ${plan}`, notIncluded: (feature, plan) => `${feature} no incluida en ${plan}` }
export function NPlanComparison({ plans, features, labels: custom, unstyled = false, classNames, styles }: NPlanComparisonProps) {
  const labels = { ...defaultNPlanComparisonLabels, ...custom }
  return <Box colorPalette="blue" overflowX="auto" borderWidth={unstyled ? undefined : "1px"} borderColor="border" rounded={unstyled ? undefined : "lg"} className={classNames?.root} css={styles?.root} data-scope="n-plan-comparison" data-part="root"><Grid minW={`${Math.max(42, plans.length * 15 + 14)}rem`} templateColumns={`minmax(14rem, 1.25fr) repeat(${plans.length}, minmax(14rem, 1fr))`} className={classNames?.grid} css={styles?.grid} data-part="grid"><Box p="4" borderBottomWidth="1px" borderColor="border"><Text fontWeight="semibold">{labels.feature}</Text></Box>{plans.map((plan) => <Card.Root unstyled={unstyled} key={plan.id} rounded={unstyled ? undefined : "0"} border={unstyled ? undefined : "0"} borderInlineStartWidth={unstyled ? undefined : "1px"} borderBottomWidth={unstyled ? undefined : "1px"} borderColor={plan.highlighted ? "colorPalette.solid" : "border"} bg={unstyled ? undefined : plan.highlighted ? "colorPalette.subtle" : "bg.panel"} className={classNames?.plan} css={styles?.plan} data-part="plan"><Card.Body unstyled={unstyled} p={unstyled ? undefined : "4"}><Stack gap="2"><Flex gap="2" align="center"><Text fontWeight="bold">{plan.name}</Text>{plan.badge}</Flex>{plan.description ? <Text textStyle="sm" color="fg.muted">{plan.description}</Text> : null}{plan.price ? <Text textStyle="2xl" fontWeight="bold">{plan.price}</Text> : null}{plan.action}</Stack></Card.Body></Card.Root>)}{features.map((feature) => [<Box key={`${feature.id}-label`} p="3" borderBottomWidth="1px" borderColor="border" className={classNames?.feature} css={styles?.feature} data-part="feature"><Text fontWeight="medium">{feature.label}</Text>{feature.description ? <Text textStyle="xs" color="fg.muted">{feature.description}</Text> : null}</Box>, ...plans.map((plan) => { const value = plan.features[feature.id]; const included = value !== false && value != null; return <Flex key={`${feature.id}-${plan.id}`} p="3" justify="center" align="center" borderInlineStartWidth="1px" borderBottomWidth="1px" borderColor="border" aria-label={included ? labels.included(String(feature.label), String(plan.name)) : labels.notIncluded(String(feature.label), String(plan.name))} className={classNames?.value} css={styles?.value} data-part="value">{typeof value === "boolean" || value == null ? <Icon color={included ? "green.fg" : "fg.muted"}>{included ? <Check /> : <Minus />}</Icon> : value}</Flex> })])}</Grid></Box>
}
